env: "local"
storage_path: "./storage/storage.db"
http_server:
  address:
  timeout: 4s
  idle_timeout: 60s
user:
  login: "user"
  password: "pass"
alias_generator:
  length: 6
  alphabet: "avc"
  gen_limit: 10